from travelogue.tests.test_effect import *
from travelogue.tests.test_travelogue import *
from travelogue.tests.test_photo import *
from travelogue.tests.test_photosize import *
from travelogue.tests.test_resize import *
from travelogue.tests.test_views_photo import *
from travelogue.tests.test_views_travelogue import *
from travelogue.tests.test_sitemap import *
from travelogue.tests.test_zipupload import *
